---
ID: "3ca98a28-8e04-47b2-a07f-233a51088f11"
Parent: "e89120fc-7229-4ff7-b653-f6d54daa6359"
Template: "e89120fc-7229-4ff7-b653-f6d54daa6359"
Path: /sitecore/templates/Foundation/Print/InlineElement/__Standard Values
DB: master
SharedFields:
- ID: "09772857-332a-4e06-a337-787f87e6c89f"
  Hint: Xml Renderer
  Value: "{DA67A910-EC5C-497F-B3C2-3194F37535C9}"
- ID: "4f3ecf8f-077e-487b-adaa-15b9554d9a62"
  Hint: Parameters
  Value: tag=Inline
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160714T121539Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\admin
