---
ID: "1cb01d00-55d9-4092-950d-9aa5b7182baa"
Parent: "ca7d256a-9971-445c-a3bb-3beba48f08d9"
Template: "ca7d256a-9971-445c-a3bb-3beba48f08d9"
Path: /sitecore/templates/Project/Legal/Content Types/Brochure/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160707T235913Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\admin
