---
ID: "120e6072-c004-4d25-9629-0d177ea64e19"
Parent: "52b69c5a-9a9d-45bf-a37e-5601e21be8ba"
Template: "52b69c5a-9a9d-45bf-a37e-5601e21be8ba"
Path: /sitecore/templates/Project/Finance/Page Types/Search Results/__Standard Values
DB: master
SharedFields:
- ID: "5585a30d-b115-4753-93ce-422c3455deb2"
  Hint: ShowInNavigation
  Type: Checkbox
  Value: 0
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r>
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{7E600430-2DEF-403E-8F1D-D6471093A8CE}">
        <r
          id="{E7AE3F87-CF66-40F2-A9F5-33ECF08BC777}"
          ph="head"
          uid="{33BC56DD-7C8D-4D7A-BDB0-B30B3D59E5CE}" />
        <r
          id="{3389CAFC-000C-41E5-921C-92821B3DB7B5}"
          ph="head"
          uid="{7B9D9E40-081E-4EAE-AE10-515E1E1FC7A1}" />
        <r
          id="{C28B9C5F-8E01-42EC-ADF6-3324FAF92C7D}"
          ph="header-top"
          uid="{31ECECA6-5803-41E6-9840-F20CA3E88234}" />
        <r
          ds="{86368A63-D78B-4C80-B774-9098BA1BF1C6}"
          id="{69B9C355-004B-4268-BB1E-2F725B8752B7}"
          ph="right-header-top"
          uid="{9043AE78-46F6-45F6-B980-5F4B541CFF25}" />
        <r
          id="{E26A158B-FA1E-4E9B-8622-E4458243FF46}"
          ph="navbar"
          uid="{965B18AD-D1A2-43A2-95E7-C62B40662503}" />
        <r
          id="{A47C8288-7D4C-45FF-B75F-4AEDBF58A02D}"
          ph="navbar-left"
          uid="{DAE6C726-63C0-4E5B-B6E9-867CD3670F3D}" />
        <r
          id="{53B085DB-6824-4941-9F28-9011CB151832}"
          ph="navbar-center"
          uid="{029D4D38-A035-4489-B4FA-CC5347D01E38}" />
        <r
          id="{8832BA30-99C3-4D20-9B1C-237D910A153F}"
          ph="navbar-right"
          uid="{59F92BE6-C625-463A-9219-6B1D9EB0225E}" />
        <r
          id="{604ECBB6-2BBF-45AF-AC6E-BA9F853E7A03}"
          ph="navbar-activity"
          uid="{F8D155D8-E0A5-42FC-947C-4EC723C90CED}" />
        <r
          id="{2695013C-DD51-410B-9983-F271F16C727D}"
          ph="navbar-activity"
          uid="{D8450DEC-24B0-4F09-A55D-ED0DEFCB95D8}" />
        <r
          ds="{3D56230C-36F0-4BBC-A75C-558EEDA21C98}"
          id="{8C3A2CFC-18FB-4BF5-8584-50EA88978ED6}"
          ph="navbar-activity"
          uid="{D8BC1020-852E-4AED-AC35-DD06DB911EC9}" />
        <r
          id="{A2216CA7-B205-4042-A345-72117D0086C3}"
          ph="page-layout"
          uid="{1AC2A215-E1EA-4F46-A4BE-33192A53C8A2}" />
        <r
          id="{D1AAD687-8B93-44C8-9011-8E8CE2DD281F}"
          ph="/page-layout/page-header"
          uid="{31FAA4B5-262A-4117-95E9-6CBD2B8BEB9A}" />
        <r
          id="{D201A487-5099-48A1-8189-55944F70C6CB}"
          par="UseStaticPlaceholderNames=1"
          ph="page-layout"
          uid="{7D0A9FD9-DF37-4DE7-9F2E-E964B376D132}" />
        <r
          id="{0AD8EC59-33EC-4103-AAD4-F3A49BFDB92C}"
          par="UseStaticPlaceholderNames=1"
          ph="/page-layout/section"
          uid="{50A3A5B3-4BB4-4156-A9DA-85C9FAF948B5}" />
        <r
          id="{E52D0AE8-2989-44E5-BEA1-EA30C17B2080}"
          par="PagesToShow=5&amp;ResultsOnPage=4"
          ph="/page-layout/section/col-huge"
          uid="{0C63A3B5-CD0C-4501-A0FF-82DCB0A685F3}" />
        <r
          id="{299FD8EA-2CFD-4A69-9CA4-7EA24CD34A46}"
          ph="footer"
          uid="{5E2E1F44-32ED-4B08-82AE-E5CC6980E5AE}" />
        <r
          id="{DE648E12-A568-4919-802E-A688EBC9B9F3}"
          par="UseStaticPlaceholderNames=1"
          ph="/footer/section"
          uid="{98A9076C-AC41-41E3-A552-27EE7986BE4F}" />
        <r
          ds="{A9B8870B-A3C3-445F-944D-BC62C3813A7F}"
          id="{F366FBA9-EF26-4007-988A-63CB64649C46}"
          ph="/footer/section/col-narrow-1"
          uid="{963A97E9-8BDD-4C13-8C1E-057087861D73}" />
        <r
          ds="{C2E57508-C70D-4C74-A4EC-360E6A18D0C7}"
          id="{F366FBA9-EF26-4007-988A-63CB64649C46}"
          ph="/footer/section/col-narrow-2"
          uid="{760E0B6D-31E4-497C-81B8-52D1611D932F}" />
        <r
          ds="{16D24062-2547-4045-BA7C-438AFC4ED3A3}"
          id="{F366FBA9-EF26-4007-988A-63CB64649C46}"
          ph="/footer/section/col-narrow-3"
          uid="{A183E54C-BAE9-4487-A607-20A233EC9EB5}" />
        <r
          ds="{856CB32B-8D72-4C5A-9A10-3B66101C5FA2}"
          id="{F366FBA9-EF26-4007-988A-63CB64649C46}"
          ph="/footer/section/col-narrow-4"
          uid="{D5D12BFA-A578-4624-AED1-07F9F9A0A3B6}" />
        <r
          id="{7DAE9F23-890F-4E06-99A7-CCEDB74D3D8E}"
          ph="postfooter"
          uid="{ADDF2612-3559-4C1C-958C-099A97B3498F}" />
        <r
          id="{CED18F24-62C2-445E-B0D9-045E3325297B}"
          ph="page-sidebar"
          uid="{21F32F1B-D642-4CE4-A427-F6D0C34D0CC6}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "0ee2f208-1fee-42fc-8051-6696d49a92bf"
      Hint: OpenGraphTitle
      Value: $name
    - ID: "1b483e91-d8c4-4d19-ba03-462074b55936"
      Hint: NavigationTitle
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150911T025049Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "80e30dd8-8021-45f5-9fe1-23d2702cc206"
      Hint: SearchBoxTitle
      Value: Enter a text to search for...
    - ID: "9492e0bb-9df9-46e7-8188-ec795c4ade44"
      Hint: Image
      Value: |
        <image mediaid="{88032F9C-B464-44CB-B76D-513D60B9C127}" />
    - ID: "c30a013f-3cc8-4961-9837-1c483277084a"
      Hint: Title
      Value: $name
    - ID: "ca0479ce-0bfe-4522-83de-ba688b380a78"
      Hint: BrowserTitle
      Value: $name
