---
ID: "ca849824-9a07-4d93-b4a5-3c3aae26fbfc"
Parent: "013a39c1-6f18-445c-9e5f-70ed2d4646d7"
Template: "013a39c1-6f18-445c-9e5f-70ed2d4646d7"
Path: /sitecore/templates/Foundation/Print/Paragraph Style/__Standard Values
DB: master
SharedFields:
- ID: "09772857-332a-4e06-a337-787f87e6c89f"
  Hint: Xml Renderer
  Value: "{46DEC53D-98D5-47A2-BB26-0EB6278006B9}"
- ID: "4f3ecf8f-077e-487b-adaa-15b9554d9a62"
  Hint: Parameters
  Value: tag=ParagraphStyle
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160615T083005Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\admin
