---
ID: 490cc202-b693-487a-b5cf-99a4c3f6a528
Parent: 1d83c3eb-ea3b-4b71-baa1-3938397fe99b
Template: 1d83c3eb-ea3b-4b71-baa1-3938397fe99b
Path: /sitecore/templates/Project/Legal/Page Types/News List/__Standard Values
DB: master
SharedFields:
- ID: 1172f251-dad4-4efb-a329-0c63500e4f1e
  Hint: __Masters
  Type: TreelistEx
  Value: {BB6A204D-2B9E-46CA-82CD-00751803B03E}
- ID: d312103c-b36c-4ca5-864a-c85f9abda503
  Hint: __Is Bucket
  Value: 1
- ID: f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e
  Hint: __Renderings
  Type: layout
  Value: |
    <r>
      <d id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}" l="{ED043C36-CD48-4EDF-A288-EC404EE1CD42}">
        <r id="{A47C8288-7D4C-45FF-B75F-4AEDBF58A02D}" ph="navbar-left" uid="{7BD25BD6-C6C4-4FBE-9828-D29A39A2FEC9}" />
        <r id="{E26A158B-FA1E-4E9B-8622-E4458243FF46}" ph="navbar" uid="{07C9FE71-A5E2-4E5F-B276-5F2B73481D44}" />
        <r id="{359A65BB-0A2C-44E5-8C34-DF3ACDBB42A7}" ph="sidebar" uid="{EB352679-4420-46AE-95B0-7CA976C24194}" />
        <r id="{3F7AD288-FA57-441F-AD79-CA60DC0C0A8D}" ph="sidebar" uid="{A85893F9-5DF5-4C28-AC0F-67AD85D29661}" />
        <r id="{E7AE3F87-CF66-40F2-A9F5-33ECF08BC777}" ph="head" uid="{E6CA18D8-321D-4105-9C38-0622E94BE400}" />
        <r id="{3389CAFC-000C-41E5-921C-92821B3DB7B5}" ph="head" uid="{EF51B238-7CE2-4E39-AB87-D05424735160}" />
        <r id="{53B085DB-6824-4941-9F28-9011CB151832}" ph="navbar-center" uid="{FBDB4313-35B5-4C26-A586-17F48FD2DC41}" />
        <r id="{8832BA30-99C3-4D20-9B1C-237D910A153F}" ph="navbar-right" uid="{75551DEC-A457-43A3-B76F-91742B5DDE93}" />
        <r id="{604ECBB6-2BBF-45AF-AC6E-BA9F853E7A03}" ph="navbar-activity" uid="{462763BC-EC80-4FBA-9714-B63A87B43259}" />
        <r id="{2695013C-DD51-410B-9983-F271F16C727D}" ph="navbar-activity" uid="{3555E24E-FBE9-4D81-AAC7-50408AA45EF0}" />
        <r id="{28BD7068-7FF6-4CE6-98E6-85CFE9967E14}" ph="navbar-activity" uid="{79242576-4E0A-4CBF-BC2B-8B0C47FE9B64}" />
        <r ds="{9AA07D42-E9B5-4B52-A0E2-4FDF08C203EE}" id="{8C3A2CFC-18FB-4BF5-8584-50EA88978ED6}" ph="navbar-activity" uid="{9C8A45F2-7008-42C1-8B8A-80A88825C1D8}" />
        <r id="{359A65BB-0A2C-44E5-8C34-DF3ACDBB42A7}" ph="page-layout" uid="{C23F233C-6D7C-44C7-9B0D-71DD1ABA5C76}" />
        <r id="{45B8E1D9-D522-49E0-B9B7-04C965CC7089}" ph="/page-layout/page-header" uid="{3CDF4DD8-28A4-4185-8C09-A73CAA4633F7}" />
        <r id="{D201A487-5099-48A1-8189-55944F70C6CB}" par="UseStaticPlaceholderNames=1" ph="page-layout" uid="{0EB115BC-CBC0-4205-8C1A-C73BA0F09F1E}" />
        <r id="{0AD8EC59-33EC-4103-AAD4-F3A49BFDB92C}" par="UseStaticPlaceholderNames=1" ph="/page-layout/section" uid="{ECCFEE95-A957-4218-8ED2-FAB94EF2CAF2}" />
        <r id="{6D309FC1-D6B1-43B1-A31C-1FECB7B9303F}" ph="/page-layout/section/col-huge" uid="{3900ADC1-26E3-45C2-935C-1BC12D4E228A}" />
        <r id="{299FD8EA-2CFD-4A69-9CA4-7EA24CD34A46}" ph="footer" uid="{E2040FB7-4151-456D-9315-5973E4EB4D9D}" />
        <r id="{7DAE9F23-890F-4E06-99A7-CCEDB74D3D8E}" ph="postfooter" uid="{A3BAD4D4-8E21-4B30-8C4C-B04163653D62}" />
        <r id="{CED18F24-62C2-445E-B0D9-045E3325297B}" ph="page-sidebar" uid="{20AB9BAA-C112-4567-A701-564423E650D2}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20150824T175428Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: sitecore\admin
    - ID: 9492e0bb-9df9-46e7-8188-ec795c4ade44
      Hint: Image
      Value: "<image mediaid=\"{88032F9C-B464-44CB-B76D-513D60B9C127}\" />"
