---
ID: "7836e72c-dbfa-4384-802a-43ccc222bc9b"
Parent: "24d19d8f-907b-47b7-9703-6174e760bd91"
Template: "24d19d8f-907b-47b7-9703-6174e760bd91"
Path: /sitecore/templates/Project/Legal/Content Types/Newsletter/Section Content/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160816T055446Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\admin
