---
ID: "ab49cab7-80dc-49db-b0e0-7eff31a7e65c"
Parent: "ddc452cb-24d1-400a-b634-589a24880b7d"
Template: "4c82b6dd-fe7c-4144-bcb3-f21b4080568f"
Path: /sitecore/content/Utilities/Settings
DB: master
BranchID: "b2e4052a-6b3b-4527-933b-e24188c76b61"
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Apps/32x32/Setting.png
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 200
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160104T045042Z
