---
ID: "fe521e70-2325-4702-9584-85b1ea2bb4de"
Parent: "f0818351-eed1-453e-8325-684eeb1a827a"
Template: "f0818351-eed1-453e-8325-684eeb1a827a"
Path: /sitecore/templates/Project/Legal/Content Types/Newsletter/Link/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160816T055436Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\admin
