---
ID: "93a6869c-a127-4712-8a8b-5fa2cca84f6b"
Parent: "c2e57508-c70d-4c74-a4ec-360e6a18d0c7"
Template: "390333c8-751b-4332-84a3-6360b969a19f"
Path: /sitecore/content/Finance/Global/Links/Footer/About/Our Vision and Values
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 200
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "1b483e91-d8c4-4d19-ba03-462074b55936"
      Hint: NavigationTitle
      Value: Our Vision and Values
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161104T042115Z
    - ID: "4231cd60-47c1-42ad-b838-0a6f8f1c4cfb"
      Hint: DividerBefore
      Type: Checkbox
      Value: 0
    - ID: "fe71c30e-f07d-4052-8594-c3028cd76e1f"
      Hint: Link
      Value: |
        <link id="{798439B8-09F8-47F2-8CDA-4194C1EDAF33}" querystring="" target="" text="" title="" class="" url="/Finance/Home/About/Vision and Values" linktype="internal" />
