---
ID: "6642410d-8a7a-4da2-bc26-0ad443899039"
Parent: "d2686e96-de4a-43f7-84ae-2027fab6b21c"
Template: "c82dc5ff-09ef-4403-96d3-3caf377b8c5b"
Path: /sitecore/content/Utilities/Settings/Datasources/searchsettings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160112T103731Z
    - ID: "498dd5b6-7dae-44a7-9213-1d32596ad14f"
      Hint: DatasourceTemplate
      Value: /sitecore/templates/Feature/Search/_SearchResults
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "5fe1cc43-f86c-459c-a379-cd75950d85af"
      Hint: DatasourceLocation
      Value: /sitecore/content/Utilities/Home
