---
ID: "3d3f8df4-ee14-498d-a2f2-a68c17ccbe85"
Parent: "75e42a73-0ae1-44c5-ac04-c9d5c4568680"
Template: "75e42a73-0ae1-44c5-ac04-c9d5c4568680"
Path: /sitecore/templates/Project/Legal/Page Types/Employee/__Standard Values
DB: master
SharedFields:
- ID: "5585a30d-b115-4753-93ce-422c3455deb2"
  Hint: ShowInNavigation
  Type: Checkbox
  Value: 0
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{E2A658AB-B142-4AD9-AACA-C69200622F44}"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r>
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{5F53E1F4-CFBA-45E4-8F86-A786EB590BAA}">
        <r
          id="{E26A158B-FA1E-4E9B-8622-E4458243FF46}"
          ph="navbar"
          uid="{07C9FE71-A5E2-4E5F-B276-5F2B73481D44}" />
        <r
          id="{359A65BB-0A2C-44E5-8C34-DF3ACDBB42A7}"
          ph="sidebar"
          uid="{EB352679-4420-46AE-95B0-7CA976C24194}" />
        <r
          id="{3F7AD288-FA57-441F-AD79-CA60DC0C0A8D}"
          ph="sidebar"
          uid="{A85893F9-5DF5-4C28-AC0F-67AD85D29661}" />
        <r
          id="{E7AE3F87-CF66-40F2-A9F5-33ECF08BC777}"
          ph="head"
          uid="{E6CA18D8-321D-4105-9C38-0622E94BE400}" />
        <r
          id="{3389CAFC-000C-41E5-921C-92821B3DB7B5}"
          ph="head"
          uid="{EF51B238-7CE2-4E39-AB87-D05424735160}" />
        <r
          id="{A47C8288-7D4C-45FF-B75F-4AEDBF58A02D}"
          ph="navbar-left"
          uid="{7BD25BD6-C6C4-4FBE-9828-D29A39A2FEC9}" />
        <r
          id="{53B085DB-6824-4941-9F28-9011CB151832}"
          ph="navbar-center"
          uid="{FBDB4313-35B5-4C26-A586-17F48FD2DC41}" />
        <r
          id="{8832BA30-99C3-4D20-9B1C-237D910A153F}"
          ph="navbar-right"
          uid="{75551DEC-A457-43A3-B76F-91742B5DDE93}" />
        <r
          id="{604ECBB6-2BBF-45AF-AC6E-BA9F853E7A03}"
          ph="navbar-activity"
          uid="{462763BC-EC80-4FBA-9714-B63A87B43259}" />
        <r
          id="{2695013C-DD51-410B-9983-F271F16C727D}"
          ph="navbar-activity"
          uid="{3555E24E-FBE9-4D81-AAC7-50408AA45EF0}" />
        <r
          id="{28BD7068-7FF6-4CE6-98E6-85CFE9967E14}"
          ph="navbar-activity"
          uid="{79242576-4E0A-4CBF-BC2B-8B0C47FE9B64}" />
        <r
          ds="{CA12194B-4464-475F-A875-8FD86080F5A4}"
          id="{3A5195F0-1269-4B20-91BB-611698515BD2}"
          ph="navbar-activity"
          uid="{AE9A972A-0AB9-483A-9AC1-2855C49E4CA0}" />
        <r
          ds="{774C6FFC-8FEE-4C84-8264-1236ED365229}"
          id="{8C3A2CFC-18FB-4BF5-8584-50EA88978ED6}"
          ph="navbar-activity"
          uid="{9C8A45F2-7008-42C1-8B8A-80A88825C1D8}" />
        <r
          id="{26B33DEB-F1DB-4338-B043-AAF2F90E04A3}"
          par="Type=bg-primary"
          ph="page-layout"
          uid="{C23F233C-6D7C-44C7-9B0D-71DD1ABA5C76}" />
        <r
          id="{B6F11192-7C7B-4DE2-9F85-140692B2470B}"
          ph="/page-layout/page-header"
          uid="{EB352679-4420-46AE-95B0-7CA976C24194}" />
        <r
          id="{C6E4CC96-91AC-4074-AD62-7DAE344F995D}"
          ph="/page-layout/page-header"
          uid="{EB352679-4420-46AE-95B0-7CA976C24194}" />
        <r
          id="{D201A487-5099-48A1-8189-55944F70C6CB}"
          par="UseStaticPlaceholderNames=1"
          ph="page-layout"
          uid="{0EB115BC-CBC0-4205-8C1A-C73BA0F09F1E}" />
        <r
          id="{0AD8EC59-33EC-4103-AAD4-F3A49BFDB92C}"
          par="UseStaticPlaceholderNames=1"
          ph="/page-layout/section"
          uid="{ECCFEE95-A957-4218-8ED2-FAB94EF2CAF2}" />
        <r
          id="{907018D8-CC53-4D34-AD67-3FDF0A25832A}"
          ph="/page-layout/section/col-huge"
          uid="{565F9960-4E47-4DA4-9406-0A29DD09911F}" />
        <r
          id="{299FD8EA-2CFD-4A69-9CA4-7EA24CD34A46}"
          ph="footer"
          uid="{E2040FB7-4151-456D-9315-5973E4EB4D9D}" />
        <r
          id="{7DAE9F23-890F-4E06-99A7-CCEDB74D3D8E}"
          ph="postfooter"
          uid="{A3BAD4D4-8E21-4B30-8C4C-B04163653D62}" />
        <r
          id="{CED18F24-62C2-445E-B0D9-045E3325297B}"
          ph="page-sidebar"
          uid="{20AB9BAA-C112-4567-A701-564423E650D2}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "0cc9785e-54fe-4fae-93e4-d0d2ae75f339"
      Hint: Biography
      Value: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris congue vulputate erat hendrerit tincidunt.
    - ID: "0ee2f208-1fee-42fc-8051-6696d49a92bf"
      Hint: OpenGraphTitle
      Value: $name
    - ID: "1b483e91-d8c4-4d19-ba03-462074b55936"
      Hint: NavigationTitle
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20151124T110516Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\admin
    - ID: "ca0479ce-0bfe-4522-83de-ba688b380a78"
      Hint: BrowserTitle
      Value: $name
