---
ID: "86cffc79-a7a0-4a7e-aded-85c116a4a3d4"
Parent: "9917c92b-0f13-4f96-b50b-84c874e25783"
Template: "9917c92b-0f13-4f96-b50b-84c874e25783"
Path: /sitecore/templates/Project/Legal/Page Types/Landing Page/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{4B0A2893-4E7B-4248-86A9-DAB6DA3BB230}"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{5F53E1F4-CFBA-45E4-8F86-A786EB590BAA}">
        <r
          id="{E7AE3F87-CF66-40F2-A9F5-33ECF08BC777}"
          ph="head"
          uid="{E6CA18D8-321D-4105-9C38-0622E94BE400}" />
        <r
          id="{3389CAFC-000C-41E5-921C-92821B3DB7B5}"
          ph="head"
          uid="{EF51B238-7CE2-4E39-AB87-D05424735160}" />
        <r
          id="{E26A158B-FA1E-4E9B-8622-E4458243FF46}"
          ph="navbar"
          uid="{07C9FE71-A5E2-4E5F-B276-5F2B73481D44}" />
        <r
          id="{A47C8288-7D4C-45FF-B75F-4AEDBF58A02D}"
          ph="navbar-left"
          uid="{7BD25BD6-C6C4-4FBE-9828-D29A39A2FEC9}" />
        <r
          id="{53B085DB-6824-4941-9F28-9011CB151832}"
          ph="navbar-center"
          uid="{FBDB4313-35B5-4C26-A586-17F48FD2DC41}" />
        <r
          id="{8832BA30-99C3-4D20-9B1C-237D910A153F}"
          ph="navbar-right"
          uid="{75551DEC-A457-43A3-B76F-91742B5DDE93}" />
        <r
          id="{604ECBB6-2BBF-45AF-AC6E-BA9F853E7A03}"
          ph="navbar-activity"
          uid="{462763BC-EC80-4FBA-9714-B63A87B43259}" />
        <r
          id="{2695013C-DD51-410B-9983-F271F16C727D}"
          ph="navbar-activity"
          uid="{3555E24E-FBE9-4D81-AAC7-50408AA45EF0}" />
        <r
          id="{28BD7068-7FF6-4CE6-98E6-85CFE9967E14}"
          ph="navbar-activity"
          uid="{79242576-4E0A-4CBF-BC2B-8B0C47FE9B64}" />
        <r
          ds="{CA12194B-4464-475F-A875-8FD86080F5A4}"
          id="{3A5195F0-1269-4B20-91BB-611698515BD2}"
          ph="navbar-activity"
          uid="{AE9A972A-0AB9-483A-9AC1-2855C49E4CA0}" />
        <r
          ds=""
          id="{8C3A2CFC-18FB-4BF5-8584-50EA88978ED6}"
          par=""
          ph="navbar-activity"
          uid="{9C8A45F2-7008-42C1-8B8A-80A88825C1D8}" />
        <r
          id="{359A65BB-0A2C-44E5-8C34-DF3ACDBB42A7}"
          ph="page-layout"
          uid="{C9B32EC2-1752-4265-9C8C-FE2B47FC2605}" />
        <r
          id="{45B8E1D9-D522-49E0-B9B7-04C965CC7089}"
          ph="/page-layout/page-header"
          uid="{60E00973-4D80-45C4-8DF0-22EBD30DFD17}" />
        <r
          id="{D201A487-5099-48A1-8189-55944F70C6CB}"
          par="UseStaticPlaceholderNames=1"
          ph="page-layout"
          uid="{826F2A9A-8690-4861-A7E5-40380F2C79C1}" />
        <r
          id="{CF750731-1275-4CC7-A9E6-809515CB4DD1}"
          par="UseStaticPlaceholderNames=1"
          ph="/page-layout/section"
          uid="{189D7C2D-4A94-40BF-8FAF-AF8A81AA81CB}" />
        <r
          id="{914673DC-FC44-4660-B6EB-FF421FAAC2F9}"
          ph="/page-layout/section/col-wide-1"
          uid="{18389D63-23B8-4E29-A9BF-EB98E18992BC}" />
        <r
          id="{299FD8EA-2CFD-4A69-9CA4-7EA24CD34A46}"
          ph="footer"
          uid="{E2040FB7-4151-456D-9315-5973E4EB4D9D}" />
        <r
          id="{D201A487-5099-48A1-8189-55944F70C6CB}"
          ph="footer"
          uid="{A4E044E8-AA9C-4D00-9923-323EE708C385}" />
        <r
          id="{7DAE9F23-890F-4E06-99A7-CCEDB74D3D8E}"
          ph="postfooter"
          uid="{A3BAD4D4-8E21-4B30-8C4C-B04163653D62}" />
        <r
          id="{CED18F24-62C2-445E-B0D9-045E3325297B}"
          ph="page-sidebar"
          uid="{20AB9BAA-C112-4567-A701-564423E650D2}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150824T175451Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "c30a013f-3cc8-4961-9837-1c483277084a"
      Hint: Title
      Value: $name
    - ID: "ca0479ce-0bfe-4522-83de-ba688b380a78"
      Hint: BrowserTitle
      Value: $name
