---
ID: f3b99db3-46ea-4a7b-a92c-46a3f188a96b
Parent: 400a5520-2c64-43e3-a5cc-adfac1b75ae3
Template: c82dc5ff-09ef-4403-96d3-3caf377b8c5b
Path: /sitecore/content/Legal/Settings/searchsettings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20160112T103731Z
    - ID: 498dd5b6-7dae-44a7-9213-1d32596ad14f
      Hint: DatasourceTemplate
      Value: /sitecore/templates/Feature/Search/_SearchResults
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: sitecore\admin
    - ID: 5fe1cc43-f86c-459c-a379-cd75950d85af
      Hint: DatasourceLocation
      Value: /sitecore/content/Legal/Home
